import "IExamQuestion.idl";
import "ExamClassificationAnswer.idl";

namespace FiberOpticCommsCourseware
{
    runtimeclass ExamClassificationQuestion : IExamQuestion
    {
        ExamClassificationQuestion(Int64 id, String text);

        Windows.Foundation.Collections.IVector<ExamClassificationAnswer> Answers { get; };
        Windows.Foundation.Collections.IVector<String> Categories { get; };
    }
}