namespace FiberOpticCommsCourseware
{
    enum ExamControlAction
    {
        Start,
        ContinueForward,
        ContinueBackward,
        QuestionSelect,
        JumpToCurrentQuestion,
        End,
        Reset
    };
}