import "IExamQuestion.idl";
import "ExamOrderingAnswer.idl";

namespace FiberOpticCommsCourseware
{
    runtimeclass ExamOrderingQuestion : IExamQuestion
    {
        ExamOrderingQuestion(Int64 id, String text);

        Windows.Foundation.Collections.IObservableVector<ExamOrderingAnswer> Answers { get; };
    }
}