namespace FiberOpticCommsCourseware
{
    runtimeclass TheoryChapter
    {
        TheoryChapter(Int64 id, String title);
        Int64 Id { get; };
        String Title { get; };
        Windows.Foundation.Collections.IObservableVector<TheoryChapter> Children { get; };
    }
}