import "TheoryChapter.idl";

namespace FiberOpticCommsCourseware
{
    [default_interface]
    runtimeclass TheoryPage : Microsoft.UI.Xaml.Controls.Page
    {
        TheoryPage();
        Windows.Foundation.Collections.IObservableVector<TheoryChapter> TheoryChapters { get; };
    }
}
