import "IExamQuestion.idl";

namespace ProPractice
{
    runtimeclass ExamFreeInputQuestion : IExamQuestion
    {
        ExamFreeInputQuestion(Int64 id, String text);

        Windows.Foundation.Collections.IVector<String> CorrectAnswers { get; };
        String UserAnswer;
    }
}