import "ExamQuestionType.idl";
import "ExamAnswer.idl";

namespace ProPractice
{
    runtimeclass ExamQuestion
    {
        ExamQuestion();

        String Text;
        ExamQuestionType Type;
        Windows.Foundation.Collections.IVector<ExamAnswer> Answers { get; };
        Object CustomDataContext;
        Boolean IsAnswered();
    };
}