import "IExamQuestion.idl";
import "ExamQuestionType.idl";
import "ExamChoiceAnswer.idl";

namespace ProPractice
{
    runtimeclass ExamChoiceQuestion : IExamQuestion
    {
        ExamChoiceQuestion(Int64 id, String text, ExamQuestionType type);

        Windows.Foundation.Collections.IObservableVector<ExamChoiceAnswer> Answers { get; };
    }
}