namespace ProPractice
{
    runtimeclass TheoryChapter : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        TheoryChapter(Int64 id, String title);
        Int64 Id;
        String Title;
        Windows.Foundation.Collections.IObservableVector<TheoryChapter> Children { get; };
    }
}